name: Build and Release Python Package

on:
	push:
		tags:
			- 'v*'

jobs:
	build:
		runs-on: ubuntu-latest
		steps:
			- name: Checkout code
				uses: actions/checkout@v4

			- name: Set up Python
				uses: actions/setup-python@v5
				with:
					python-version: '3.10'

			- name: Install dependencies
				run: |
					python -m pip install --upgrade pip
					pip install -r requirements.txt

			- name: Install build dependencies
				run: |
					pip install build

			- name: Build package
				run: |
					python -m build

			- name: Upload package to release
				uses: softprops/action-gh-release@v1
				with:
					files: dist/*
				env:
					GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
